import { KpiCard, StatusBadge } from '@/components/ui';

const overdue = [
  ['REC-2026-014', 'Direction Crédits', 'En retard', 'Critique'],
  ['REC-2026-021', 'Conformité', 'En attente justificatif', 'Haute'],
  ['REC-2026-033', 'Opérations', 'Demande de prorogation', 'Moyenne'],
];

export default function Page() {
  return <section className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Vue comité</p><h1 className="text-3xl font-bold text-slate-950">Dashboard de suivi des recommandations</h1><p className="mt-2 text-slate-600">Synthèse consolidée par statut, entité, source, criticité, échéance et avancement.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><KpiCard label="Recommandations" value="128" hint="+18 depuis le dernier import" tone="blue" /><KpiCard label="Taux d’avancement" value="64%" hint="pondéré par les actions" tone="emerald" /><KpiCard label="En retard" value="17" hint="échéance dépassée ou prorogation ouverte" tone="red" /><KpiCard label="Critiques" value="9" hint="criticité haute et probabilité élevée" tone="amber" /></div><div className="grid gap-4 xl:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Répartition par workflow</h2><div className="mt-4 space-y-3">{['Brouillon', 'Ouverte', 'En cours', 'En attente justificatif', 'Réalisée', 'Validée', 'Clôturée', 'Rejetée'].map((status, index) => <div key={status}><div className="flex justify-between text-sm"><span>{status}</span><span>{12 + index * 3}</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${20 + index * 8}%` }} /></div></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Alertes prioritaires</h2><div className="mt-4 divide-y divide-slate-100">{overdue.map(([code, entity, status, severity]) => <div key={code} className="flex items-center justify-between py-3"><div><p className="font-semibold">{code}</p><p className="text-sm text-slate-500">{entity}</p></div><div className="flex gap-2"><StatusBadge tone="red">{status}</StatusBadge><StatusBadge tone="amber">{severity}</StatusBadge></div></div>)}</div></article></div></section>;
}
